"""
Inference Engine — Mock and Real (vLLM) implementations.

Controlled by the USE_MOCK environment variable:
  USE_MOCK=true  → MockEngine: simulates token generation with asyncio.sleep
  USE_MOCK=false → VLLMEngine: real inference via vLLM AsyncLLMEngine

Both engines expose the same async generator interface:
    async def generate(prompt: str, request_id: str, max_tokens: int, temperature: float)
        -> AsyncGenerator[str, None]
"""

import os
import asyncio
import logging
from typing import AsyncGenerator

logger = logging.getLogger(__name__)

USE_MOCK = os.getenv("USE_MOCK", "true").lower() == "true"
MODEL_PATH = os.getenv("MODEL_PATH", "TinyLlama/TinyLlama-1.1B-Chat-v1.0")

# Simulated responses for the mock engine
MOCK_RESPONSES = [
    "This is a simulated response from the mock inference engine. "
    "In production this would be generated by a real language model.",
    "Hello! I am a mock language model. I generate fake tokens at a "
    "configurable speed to simulate real inference latency.",
    "The quick brown fox jumps over the lazy dog. "
    "This sentence contains every letter of the alphabet.",
    "I am running in mock mode. To use a real model, set USE_MOCK=false "
    "and provide a valid MODEL_PATH environment variable.",
]


class MockEngine:
    """
    Simulates token-by-token generation with a configurable delay.
    Useful for local development and testing without a GPU.
    """

    def __init__(self, tokens_per_second: float = 20.0):
        self.delay = 1.0 / tokens_per_second
        self._response_index = 0
        logger.info(
            f"MockEngine initialised at {tokens_per_second} tokens/sec"
        )

    async def generate(
        self,
        prompt: str,
        request_id: str,
        max_tokens: int = 200,
        temperature: float = 0.7,
    ) -> AsyncGenerator[str, None]:
        """
        Yields tokens one at a time with a simulated delay.
        Cycles through MOCK_RESPONSES to vary output.
        """
        response = MOCK_RESPONSES[
            self._response_index % len(MOCK_RESPONSES)
        ]
        self._response_index += 1

        # Tokenise by splitting on spaces (simplified)
        tokens = response.split()
        tokens = tokens[:max_tokens]

        logger.debug(
            f"MockEngine generating {len(tokens)} tokens "
            f"for request_id={request_id}"
        )

        for i, token in enumerate(tokens):
            await asyncio.sleep(self.delay)
            # Add space prefix to all tokens except the first
            yield token if i == 0 else f" {token}"


class VLLMEngine:
    """
    Real inference engine backed by vLLM's AsyncLLMEngine.
    Requires a CUDA-capable GPU and vLLM installed.
    """

    def __init__(self):
        # Import vLLM lazily so the module loads without GPU in mock mode
        try:
            from vllm import AsyncLLMEngine, AsyncEngineArgs, SamplingParams
            self._SamplingParams = SamplingParams
        except ImportError:
            raise RuntimeError(
                "vLLM is not installed. "
                "Install it with: pip install vllm"
            )

        logger.info(f"Initialising vLLM engine with model: {MODEL_PATH}")
        engine_args = AsyncEngineArgs(
            model=MODEL_PATH,
            dtype="float16",
            max_model_len=2048,
            gpu_memory_utilization=0.90,
        )
        self.engine = AsyncLLMEngine.from_engine_args(engine_args)
        logger.info("vLLM engine ready.")

    async def generate(
        self,
        prompt: str,
        request_id: str,
        max_tokens: int = 200,
        temperature: float = 0.7,
    ) -> AsyncGenerator[str, None]:
        """
        Streams tokens from vLLM's async generator.
        Yields delta tokens (new text only, not cumulative).
        """
        sampling_params = self._SamplingParams(
            temperature=temperature,
            max_tokens=max_tokens,
        )

        previous_text = ""
        async for output in self.engine.generate(
            prompt, sampling_params, request_id
        ):
            new_text = output.outputs[0].text
            delta = new_text[len(previous_text):]
            previous_text = new_text
            if delta:
                yield delta


def create_engine():
    """Factory function — returns the appropriate engine based on config."""
    if USE_MOCK:
        logger.info("Using MockEngine (USE_MOCK=true)")
        return MockEngine(tokens_per_second=20.0)
    else:
        logger.info("Using VLLMEngine (USE_MOCK=false)")
        return VLLMEngine()